Closes #116: update path
RConsortium/submissions-pilot3-adam pull request #117
Opened 2023-06-30 21:33 UTC by kaz462

2023-06-30 21:39 UTC, kaz462 commented
@laxamanaj I've tested and rerun the QC programs after the path updates, datasets and outputs remain the same

2023-07-05 23:37 UTC, laxamanaj commented
Thanks, @kaz462 .

Are you able to fix the auto checks that are not passing? 

cc: @bms63

2023-07-06 00:49 UTC, kaz462 commented
@bms63 could you help take a look? I tried to [update r-cmd-check.yml](https://github.com/RConsortium/submissions-pilot3-adam/pull/117/commits/43fc92a0e3e9b75ada3ac9f5e265b4ef4cc786b3), but the checks are still failing.

2023-07-06 12:32 UTC, bms63 commented
@laxamanaj didn't we place pilot3 repo into the lock file?  Did that get merged into `main`?

2023-07-06 15:28 UTC, laxamanaj commented
> @laxamanaj didn't we place pilot3 repo into the lock file? Did that get merged into `main`?

Hi, @bms63 .  Yes, I thought we did include pilot3 package in the lock file, but I saw that it wasn't there.  I even did a renv::snapshot(), but the pilot3 package wouldn't show in the lock file. That's why in the adrg, I just added the step for the reviewers to install pilot3 seperately.

2023-07-06 15:39 UTC, laxamanaj requested changes
added some minor comments.  Thanks, @kaz462 !

2023-07-06 15:39 UTC, laxamanaj commented on submission/programs/tlf-demographic.r
> +#   output = "path/to/esub/analysis/output",  # Modify path to the adam location
the comment here, should say #Modify path to the output location.

2023-07-06 15:39 UTC, laxamanaj commented on submission/programs/tlf-efficacy.r
> +#   output = "path/to/esub/analysis/output",  # Modify path to the adam location
the comment here, should say #Modify path to the output location.

2023-07-06 15:39 UTC, laxamanaj commented on submission/programs/tlf-kmplot.r
> +#   output = "path/to/esub/analysis/output",  # Modify path to the adam location
the comment here, should say #Modify path to the output location.

2023-07-06 15:39 UTC, laxamanaj commented on submission/programs/tlf-primary.r
> +#   output = "path/to/esub/analysis/output",  # Modify path to the adam location
the comment here, should say #Modify path to the output location.

2023-07-06 18:06 UTC, laxamanaj commented on submission/programs/tlf-efficacy.r
> +#   output = "path/to/esub/analysis/output",  # Modify path to the adam location
Hi, @kaz462 .  I went ahead and updated the comment so that I can merge and run the scripts and continue testing.

2023-07-06 18:06 UTC, laxamanaj commented on submission/programs/tlf-kmplot.r
> +#   output = "path/to/esub/analysis/output",  # Modify path to the adam location
Hi, @kaz462 .  I went ahead and updated the comment so that I can merge and run the scripts and continue testing.

2023-07-06 18:07 UTC, laxamanaj commented on submission/programs/tlf-primary.r
> +#   output = "path/to/esub/analysis/output",  # Modify path to the adam location
Hi, @kaz462 .  I went ahead and updated the comment so that I can merge and run the scripts and continue testing.

2023-07-06 18:08 UTC, laxamanaj approved these changes
updates looks good. Thanks, @kaz462 .

2023-07-06 21:40 UTC, merged

2023-07-07 16:27 UTC, kaz462 commented
Thanks a lot! @bms63 @laxamanaj