updating README with new snapshot information
RConsortium/submissions-pilot3-adam pull request #22
Opened 2022-11-21 19:11 UTC by nicolekjones

This is to address issue #12 to update readme with new snapshot information

2022-11-22 07:31 UTC, thomas-neitmann commented
Thanks a lot @nicolekjones! Can you also update the info in the `DESCRIPTION` file?

2022-11-28 13:43 UTC, nicolekjones commented
@thomas-neitmann updates to description/project were handled in envsetup branch. Pulled their updates into this one to avoid any merge conflicts

2022-11-29 16:59 UTC, thomas-neitmann requested changes

2022-11-29 16:59 UTC, thomas-neitmann commented on README.md
> +The [RConsortium/submissions-pilot1](https://github.com/RConsortium/submissions-pilot3-adam) repo demonstrates an approach to organize internal developed R function ADaM generation program using an R
```suggestion
The [RConsortium/submissions-pilot3-adam](https://github.com/RConsortium/submissions-pilot3-adam) repo demonstrates an approach to organize internal developed R function ADaM generation program using an R package. 
```

2022-11-29 18:24 UTC, thomas-neitmann approved these changes

2022-11-29 18:24 UTC, merged