regenerate output for demographic
RConsortium/submissions-pilot3-adam pull request #65
Opened 2023-02-24 16:47 UTC by wangben718

Difference found:
1. Decimal digits
2. Line 31: min -max for high dose was 13.7 - 34.5

2023-03-03 20:53 UTC, laxamanaj requested changes
Hi, @wangben718 

I added some minor comments.  Hope they can be updated soon.  Thanks.

Joel

2023-03-03 20:53 UTC, laxamanaj commented on output/tlf-demographic.out.pilot3
> +Program: tlf_demographic.Rmd
Change footnote to say `Program: tlf_demographic.R` .

2023-03-03 20:53 UTC, laxamanaj commented on output/tlf-demographic.out.pilot3
> +
For the filename of the output, can you please update to `tlf-demographic-pilot3.out`?

2023-03-09 22:33 UTC, laxamanaj commented
Hi, @wangben718 .  Thanks for pushing for review.  One question, did you also push the script which creates the output, `tlf-demographic.R`.  In this PR, when I click on files changed I only see the `tlf-demographic-pilot3.out` has changed, but I don't see the script updates.
![image](https://user-images.githubusercontent.com/95468392/224175454-744d8bfe-5a4f-40b0-ab28-7fa2e999acab.png)

2023-03-10 03:46 UTC, wangben718 commented
> Hi, @wangben718 . Thanks for pushing for review. One question, did you also push the script which creates the output, `tlf-demographic.R`. In this PR, when I click on files changed I only see the `tlf-demographic-pilot3.out` has changed, but I don't see the script updates. ![image](https://user-images.githubusercontent.com/95468392/224175454-744d8bfe-5a4f-40b0-ab28-7fa2e999acab.png)

Hi @laxamanaj , I have updated the tlf-demographic.R. I got a little confused about the workflow. So now we are not using `.rmd` any more and we revised `.R` file directly when re-creating TLFs for submission. Is that correct?

2023-03-10 18:59 UTC, laxamanaj commented on output/tlf-demographic.out.pilot3
> +
this is fixed.  Thanks, @wangben718 !

2023-03-10 19:00 UTC, laxamanaj commented on output/tlf-demographic.out.pilot3
> +Program: tlf_demographic.Rmd
This is fixed.  Thanks, @wangben718 .

2023-03-10 19:01 UTC, laxamanaj approved these changes
Thanks for the udpates, @wangben718 . I also wanted to note that I just updated the scripts so that the extension are now `.R` instead of `.r`.

2023-03-30 17:11 UTC, laxamanaj commented
> > Hi, @wangben718 . Thanks for pushing for review. One question, did you also push the script which creates the output, `tlf-demographic.R`. In this PR, when I click on files changed I only see the `tlf-demographic-pilot3.out` has changed, but I don't see the script updates. ![image](https://user-images.githubusercontent.com/95468392/224175454-744d8bfe-5a4f-40b0-ab28-7fa2e999acab.png)
> 
> Hi @laxamanaj , I have updated the tlf-demographic.R. I got a little confused about the workflow. So now we are not using `.rmd` any more and we revised `.R` file directly when re-creating TLFs for submission. Is that correct?

That's correct, @wangben718 .  The .R script and demog table output looks good now.  I will merge.

2023-03-30 17:11 UTC, merged